services:
  yocto:
    build:
      context: .
      dockerfile: Dockerfile
    user: ${DOCKER_USER?created files will be owned by UID:GID on host}
    volumes:
      - .:/opt/poky/meta-redengin:ro
      - ./build:/tmp/build
    working_dir: /tmp/build
    environment:
      - MACHINE=${YOCTO_MACHINE}
    # command: --help