services:
  crops:
    build:
      context: .
      dockerfile: Dockerfile
    # user: ${DOCKER_USER?created files will be owned by UID:GID on host}
    user: ${DOCKER_USER:-0:0} # default to root access
    volumes:
      - .:/tmp/meta-redengin:ro
      - ./build:/tmp/build
    working_dir: /tmp/build