services:
  crops:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    # user: ${DOCKER_USER?created files will be owned by UID:GID on host}
    user: ${DOCKER_USER:-0:0} # default to root ownership
    volumes:
      - .:/tmp/meta-redengin:ro
      - ./build/conf:/tmp/build/conf:ro
      - ${BUILD_DIR}:/tmp/build
    working_dir: /tmp/build

  qemu-kvm:
    privileged: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    # user: ${DOCKER_USER?created files will be owned by UID:GID on host}
    user: ${DOCKER_USER:-0:0} # default to root ownership
    volumes:
      - .:/tmp/meta-redengin:ro
      - ./build/conf:/tmp/build/conf:ro
      - ${BUILD_DIR}:/tmp/build
    working_dir: /tmp/build
    command:
      - runqemu
      - /tmp/build/tmp-glibc/deploy/images/qemux86-64
      - kvm
      - slirp
      - serialstdio

  toaster:
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile
      target: toaster
    # user: ${DOCKER_USER?created files will be owned by UID:GID on host}
    user: ${DOCKER_USER:-0:0} # default to root ownership
    volumes:
      - .:/tmp/meta-redengin:ro
      - ./build/conf:/tmp/build/conf:ro
      - ${BUILD_DIR}:/tmp/build
    working_dir: /tmp/build
    environment:
      - BUILDDIR=/tmp/build